// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/products/:handle": {
    params: {
      "handle": string;
    };
  };
  "/services": {
    params: {};
  };
  "/health": {
    params: {};
  };
  "/about": {
    params: {};
  };
  "/staff": {
    params: {};
  };
  "/cart": {
    params: {};
  };
  "/shop": {
    params: {};
  };
  "/graphiql": {
    params: {};
  };
  "/subrequest-profiler": {
    params: {};
  };
  "/.well-known/appspecific/com.chrome.devtools.json": {
    params: {};
  };
};

type RouteFiles = {
  "root.jsx": {
    id: "root";
    page: "/" | "/products/:handle" | "/services" | "/health" | "/about" | "/staff" | "/cart" | "/shop" | "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "routes/products.$handle.jsx": {
    id: "routes/products.$handle";
    page: "/products/:handle";
  };
  "routes/services.jsx": {
    id: "routes/services";
    page: "/services";
  };
  "routes/_index.jsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/health.jsx": {
    id: "routes/health";
    page: "/health";
  };
  "routes/about.jsx": {
    id: "routes/about";
    page: "/about";
  };
  "routes/staff.jsx": {
    id: "routes/staff";
    page: "/staff";
  };
  "routes/cart.jsx": {
    id: "routes/cart";
    page: "/cart";
  };
  "routes/shop.jsx": {
    id: "routes/shop";
    page: "/shop";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout.jsx": {
    id: "/Users/gongahkia/Desktop/coding/startup/light-form-frontend/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout";
    page: "/graphiql" | "/subrequest-profiler" | "/.well-known/appspecific/com.chrome.devtools.json" | "/";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/graphiql.jsx": {
    id: "vite/virtual-routes/routes/graphiql";
    page: "/graphiql";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/subrequest-profiler.jsx": {
    id: "vite/virtual-routes/routes/subrequest-profiler";
    page: "/subrequest-profiler";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json.jsx": {
    id: "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json";
    page: "/.well-known/appspecific/com.chrome.devtools.json";
  };
  "../node_modules/@shopify/hydrogen/dist/vite/virtual-routes/routes/index.jsx": {
    id: "vite/virtual-routes/routes/index";
    page: "/";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.jsx");
  "routes/products.$handle": typeof import("./app/routes/products.$handle.jsx");
  "routes/services": typeof import("./app/routes/services.jsx");
  "routes/_index": typeof import("./app/routes/_index.jsx");
  "routes/health": typeof import("./app/routes/health.jsx");
  "routes/about": typeof import("./app/routes/about.jsx");
  "routes/staff": typeof import("./app/routes/staff.jsx");
  "routes/cart": typeof import("./app/routes/cart.jsx");
  "routes/shop": typeof import("./app/routes/shop.jsx");
  "/Users/gongahkia/Desktop/coding/startup/light-form-frontend/node_modules/@shopify/hydrogen/dist/vite/virtual-routes/layout": unknown;
  "vite/virtual-routes/routes/graphiql": unknown;
  "vite/virtual-routes/routes/subrequest-profiler": unknown;
  "vite/virtual-routes/routes/[.]well-known.appspecific.com[.]chrome[.]devtools[.]json": unknown;
  "vite/virtual-routes/routes/index": unknown;
};